Repository Runroom/ui, pull requests merged in 2020-04, with the labels that each got.

#31 Add Conventions File and document PureJS dependency
  README.md
  conventions.md
Labels: documentation

#11 Add switch component
  packages/ui/components/skip-links/styles.css
  packages/ui/components/switch/index.twig
  packages/ui/components/switch/styles.css
  packages/ui/components/switch/styles.scss
  packages/ui/components/switch/switch.md
  packages/ui/components/switch/switch.twig
  packages/ui/components/toggle/scripts.min.js
  web/assets/img/switch.png
  web/config/structure.js
  web/pages/switch.js
  yarn.lock
Labels: enhancement

#21 Feature/scroll top
  packages/ui/components/foo/scripts.min.js
  packages/ui/components/incremental/scripts.min.js
  packages/ui/components/responsiveTable/scripts.min.js
  packages/ui/components/scrollTop/index.twig
  packages/ui/components/scrollTop/scripts.js
  packages/ui/components/scrollTop/scripts.min.js
  packages/ui/components/scrollTop/scrollTop.md
  packages/ui/components/scrollTop/scrollTop.twig
  packages/ui/components/scrollTop/styles.css
  packages/ui/components/scrollTop/styles.scss
  packages/ui/components/toggle/scripts.min.js
  web/config/structure.js
  web/pages/scroll-top.js
  yarn-error.log
Labels: enhancement

#41 Fixes pages
  packages/ui/components/link/link.twig
  packages/ui/components/skip-links/styles.css
  packages/ui/components/skip-links/styles.scss
  web/config/structure.js
  web/pages/link.js
  web/pages/skip-links.js
Labels: bug
